DROP TABLE IF EXISTS compilations_events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE users
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email  VARCHAR(255),
    name   VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE categories
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE events
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_published TIMESTAMP WITHOUT TIME ZONE,
    date_created TIMESTAMP WITHOUT TIME ZONE,
    date_event   TIMESTAMP WITHOUT TIME ZONE,
    state INT,
    title VARCHAR(255),
    annotation  VARCHAR(2000),
    description VARCHAR(7000),
    initiator_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id INT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    paid BOOLEAN NOT NULL,
    participant_limit INT,
    request_moderation BOOLEAN,
    lat NUMERIC,
    lon NUMERIC,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE requests
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_id INT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    date TIMESTAMP WITHOUT TIME ZONE,
    status INT,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE compilations
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    pinned BOOLEAN,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE compilations_events
(
    event_id INT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    compilation_id INT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT pk_compilation_event PRIMARY KEY (event_id, compilation_id)
);

CREATE TABLE comments
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  INT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_id INT                                  NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    date     TIMESTAMP WITHOUT TIME ZONE,
    text     VARCHAR(2000),
    edited   BOOLEAN,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);
